name: Badge Creation

on:
  push:
    branches: [ main, 'badge/*', 'doc/*', 'dev/*' ]

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8.17'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download cloc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          cloc .
          echo "CODE_LINES=$(./cloc.sh --loc)" >> $GITHUB_ENV
          echo "COMMENT_LINES=$(./cloc.sh --percentage)%" >> $GITHUB_ENV
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.BADGE_GIST_ID }}
          filename: loc.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: lightgrey
      - name: Create Comments-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.BADGE_GIST_ID }}
          filename: comments.json
          label: Comments
          message: ${{ env.COMMENT_LINES }}
          color: green
